app/mod_users/controllers.py
from flask import Blueprint, request, render_template, abort, \
                  flash, g, session, redirect, url_for
from app import app, db
from app.mod_users.models import User

mod_users = Blueprint('users', __name__, url_prefix='/users')

@mod_users.route('/')
def index():
  page = 1 if request.args.get('page')==None else int(request.args.get('page'))
  users = User.query.paginate(page, app.config["ITEMS_PER_PAGE"], False)
  return render_template('users/index.html', users=users)

@mod_users.route('/<username>')
def show(username):
  user = User.query.filter_by(username=username).first()
  if not user:
    flash('User does not exist')
    return redirect(url_for('users.index'))
  return render_template('users/show.html', user=user)

app/templates/users/index.html
{% extends "layouts/application.html" %}
{% block body %}
  {% from "_paginationhelpers.html" import render_pagination %}
  <ul class=tasks>
    {% for user in users.items %}
      <li>
        <h2>
          {{ user.username }}
          <small>
            <a href="{{ url_for('users.show', username=user.username) }}">view</a>
          </small>
        </h2>
        name: {{ user }}
      </li>
    {% else %}
      <li><em>Unbelievable.  No users here so far</em></li>
    {% endfor %}
  </ul>
  {{ render_pagination(users, 'users.index') }}
{% endblock %}

app/templates/users/show.html
{% extends "layouts/application.html" %}
{% block body %}
  <dl>
    <dt>username</dt>
    <dd>{{ user.username }}</dd>
    <dt>first name</dt>
    <dd>{{ user.first_name }}</dd>
    <dt>last name</dt>
    <dd>{{ user.last_name }}</dd>
  </dl>

  {% from "tasks/_tasks_list.html" import render_tasks_list %}
  <h2>Tasks Added</h2>
  {{ render_tasks_list(user.added_tasks) }}

  <h2>Tasks Completed</h2>
  {{ render_tasks_list(user.completed_tasks) }}
{% endblock %}