app/mod_tasks/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, abort, \
                  flash, g, session, redirect, url_for

# Import the database object from the main app module
from app import app, db

# Import module forms
from app.mod_tasks.forms import TaskForm

# Import module models (i.e. User)
from app.mod_tasks.models import Task
from app.mod_users.models import User

# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_tasks = Blueprint('tasks', __name__, url_prefix='/tasks')

# Set the route and accepted methods
@mod_tasks.route('/')
def index():
  fltr = request.args.get('s')
  page = 1 if request.args.get('page')==None else int(request.args.get('page'))
  tasks = Task.query
  if fltr == 'c':
    tasks = Task.query.filter(Task.completed_by != None)
  elif fltr == 'nc':
    tasks = Task.query.filter_by(completed_by=None)
  tasks = tasks.paginate(page, app.config["ITEMS_PER_PAGE"], False)
  return render_template('tasks/index.html', tasks=tasks)

@mod_tasks.route('/new', methods=['GET'])
def new():
  if not session.get('logged_in'):
    abort(401)
  form = TaskForm(request.form)
  return render_template('tasks/new.html', form=form)

@mod_tasks.route('/create', methods=['POST'])
def create():
  if not session.get('logged_in'):
    abort(401)
  form = TaskForm(request.form)

  if form.validate():
    task = Task(form.title.data, form.description.data, User.query.get(session.get('user_id')))
    db.session.add(task)
    db.session.commit()
    flash('Task was successfully posted')
    return redirect(url_for('tasks.index'))
  else:
    flash('Validations failed')
  return render_template('tasks/new.html', form=form)

@mod_tasks.route('/<id>', methods=['GET'])
def show(id):
  task = Task.query.get(id)
  if not task:
    flash('Task does not exist')
    return redirect(url_for('tasks.index'))
  return render_template('tasks/show.html', task=task)

@mod_tasks.route('/<id>/complete', methods=['POST'])
def complete(id):
  if not session.get('logged_in'):
    abort(401)
  task = Task.query.get(id)
  if not task:
    flash('Task does not exist')
    return redirect(url_for('index'))
  if task.completed_by:
    flash('Task is already completed')
    return redirect(url_for('tasks.show', id=task.id))
  task.complete(User.query.get(session.get('user_id')))
  db.session.add(task)
  db.session.commit()
  flash('Task successfully completed')
  return redirect(url_for('tasks.show', id=task.id))

@mod_tasks.route('/<id>/delete', methods=['POST'])
def delete(id):
  if not session.get('logged_in'):
    abort(401)
  task = Task.query.get(id)
  if not task:
    flash('Task does not exist')
    return redirect(url_for('index'))
  if task.completed_by:
    flash('Task is already completed. Unable to delete')
    return redirect(url_for('tasks.show', id=task.id))
  db.session.delete(task)
  db.session.commit()
  flash('Task successfully deleted')
  return redirect(url_for('tasks.index'))

app/templates/tasks/_tasks_list.html
{% macro render_tasks_list(tasks) %}
<ul>
  {% for task in tasks %}
    <li>
      <h2>
        {{ task.title }}
        <small>
          <a href="{{ url_for('tasks.show', id=task.id) }}">view</a>
        </small>
      </h2>
    </li>
  {% else %}
    <li><em>No tasks added</em></li>
  {% endfor %}
</ul>
{% endmacro %}

app/templates/tasks/index.html
{% extends "layouts/application.html" %}
{% block body %}
  {% from "_paginationhelpers.html" import render_pagination %}
  <ul>
    <li>
      <a href="{{ url_for('tasks.index') }}">show all</a>
    </li>
    <li>
      <a href="{{ url_for('tasks.index', s='c') }}">show completed</a>
    </li>
    <li>
      <a href="{{ url_for('tasks.index', s='nc') }}">show not yet completed</a>
    </li>
  </ul>
  <ul class=tasks>
    {% for task in tasks.items %}
      <li>
        <h2>
          {{ task.title }}
          <small>
            <a href="{{ url_for('tasks.show', id=task.id) }}">view</a>
          </small>
        </h2>
        added by {{ task.added_by }}, completed by {{ task.completed_by }}
      </li>
    {% else %}
      <li><em>Unbelievable.  No tasks here so far</em></li>
    {% endfor %}
  </ul>
  {{ render_pagination(tasks, 'tasks.index') }}
{% endblock %}

app/templates/tasks/new.html
{% extends "layouts/application.html" %}
{% block body %}
  {% if session.logged_in %}
    {% from "_formhelpers.html" import render_field %}
    <form action="{{ url_for('tasks.create') }}" method=post class=new-task>
      {{ form.csrf_token }}
      <dl>
        {{ render_field(form.title) }}
        {{ render_field(form.description) }}
        <dd><input type="submit" name="submit" value="Post"></dd>
      </dl>
    </form>
  {% endif %}
{% endblock %}

app/templates/tasks/show.html
{% extends "layouts/application.html" %}
{% block body %}
{% if session.logged_in %}
  {% if not task.completed_by %}
    <form action="{{ url_for('tasks.complete', id=task.id) }}" method=post class=complete>
      <input type="submit" name="submit" value="Complete">
    </form>
    <form action="{{ url_for('tasks.delete', id=task.id) }}" method=post class=delete>
      <input type="submit" name="submit" value="Delete">
    </form>
  {% endif %}
{% endif %}
<dl>
  <dt>Title</dt>
  <dd>{{ task.title }}</dd>
  <dt>Description</dt>
  <dd>{{ task.description }}</dd>
  <dt>Added By</dt>
  <dd>{{ task.added_by }}</dd>
  <dt>Created At</dt>
  <dd>{{ task.created_at }}</dd>
  <dt>Completed By</dt>
  <dd>{{ task.completed_by }}</dd>
  <dt>Completed At</dt>
  <dd>{{ task.completed_at }}</dd>
</dl>
{% endblock %}